from abc import ABC, abstractmethod
from typing import List, Tuple, Any, Optional

class QKDProtocol(ABC):
    """
    Abstract base class for Quantum Key Distribution protocols.
    Defines the standard interface for bits/basis generation, encoding, measurement, and sifting.
    """
    @property
    @abstractmethod
    def name(self) -> str:
        """The name of the protocol."""
        pass

    @abstractmethod
    def generate_bits(self, n: int) -> List[int]:
        """
        Generate random bits for Alice.

        Args:
            n: Number of bits to generate.

        Returns:
            A list of n random bits (0 or 1).
        """
        pass

    @abstractmethod
    def generate_alice_bases(self, n: int) -> List[str]:
        """
        Generate random bases for Alice's encoding.

        Args:
            n: Number of bases to generate.

        Returns:
            A list of n basis strings (e.g., 'Z', 'X').
        """
        pass

    @abstractmethod
    def generate_bases(self, n: int) -> List[str]:
        """
        Generate random bases for Bob's measurement.

        Args:
            n: Number of bases to generate.

        Returns:
            A list of n basis strings.
        """
        pass

    @abstractmethod
    def encode(self, bits: List[int], bases: List[str]) -> List[Any]:
        """
        Encode bits into quantum circuits using the given bases.

        Args:
            bits: List of bits to encode.
            bases: List of bases to use for encoding.

        Returns:
            A list of Qiskit QuantumCircuit objects.
        """
        pass

    @abstractmethod
    def measure(self, circuits: List[Any], bases: List[str], backend: Optional[Any] = None) -> Tuple[List[int], List[Any]]:
        """
        Measure the quantum circuits using the given bases.

        Args:
            circuits: List of QuantumCircuit objects to measure.
            bases: List of bases to use for measurement.
            backend: Optional Qiskit backend to run the simulation on.

        Returns:
            A tuple containing (results, measurement_circuits).
        """
        pass

    @abstractmethod
    def sift(self, alice_bases: List[str], bob_bases: List[str], alice_bits: List[int], bob_bits: List[int]) -> Tuple[List[int], List[int], List[int]]:
        """
        Perform key sifting based on basis matching.

        Args:
            alice_bases: Bases used by Alice for encoding.
            bob_bases: Bases used by Bob for measurement.
            alice_bits: Original bits generated by Alice.
            bob_bits: Measurement results obtained by Bob.

        Returns:
            A tuple containing (sifted_alice_key, sifted_bob_key, indices).
        """
        pass
